version: '3'
services:
  vyos01:
    hostname: vyos01
    container_name: vyos01
    image: 2stacks/vyos:latest
    command: /sbin/init
    volumes:
    - /lib/modules:/lib/modules
    privileged: true
    networks:
      mgmt_nw:
        ipv4_address: 10.0.0.3

  vyos02:
    hostname: vyos02
    container_name: vyos02
    image: 2stacks/vyos:latest
    command: /sbin/init
    volumes:
    - /lib/modules:/lib/modules
    privileged: true
    networks:
      mgmt_nw:
        ipv4_address: 10.0.0.4

networks:
  mgmt_nw:
    name: mgmt_nw
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
