---
- hosts: vyos
  gather_facts: false
  tasks:
    - name: show configuration commands
      vyos_command:
        commands:
          - show configuration commands
      register: result_conf

    - name: debug config
      debug:
        msg: "{{ result_conf.stdout_lines[0] }}"

    - name: show ip route
      vyos_command:
        commands:
          - show ip route
      register: result_route

    - name: debug route
      debug:
        msg: "{{ result_route.stdout_lines[0] }}"

    - name: decrease distance for eth2 at vyos01
      vyos_config:
        lines:
          - set protocols static route 2.2.2.2/32 next-hop 172.31.2.4 distance '5'
      when: inventory_hostname == 'vyos01'

    - name: decrease distance for eth2 at vyos02
      vyos_config:
        lines:
          - set protocols static route 1.1.1.1/32 next-hop 172.31.2.3 distance '5'
      when: inventory_hostname == 'vyos02'


    - name: show configuration commands
      vyos_command:
        commands:
          - show configuration commands
      register: result_conf

    - name: debug config
      debug:
        msg: "{{ result_conf.stdout_lines[0] }}"

    - name: show ip route
      vyos_command:
        commands:
          - show ip route
      register: result_route

    - name: debug route
      debug:
        msg: "{{ result_route.stdout_lines[0] }}"
