---
- hosts: vyos
  gather_facts: false
  tasks:
  - name: show conf before
    vyos_command:
      commands:
        - show configuration command
    register: result
  
  - name: debug config
    debug:
      msg: "{{ result.stdout_lines[0] }}"

  - name: set conf vyos01
    vyos_config:
      lines: 
        - set interfaces ethernet eth0 address 10.0.0.3/24
        - set interfaces ethernet eth1 address 172.31.1.3/24
        - set interfaces ethernet eth2 address 172.31.2.3/24
        - set interfaces loopback lo address 1.1.1.1/32
        - set protocols static route 2.2.2.2/32 next-hop 172.31.1.4 distance '10'
        - set protocols static route 2.2.2.2/32 next-hop 172.31.2.4 distance '15'
      save: yes
    when: inventory_hostname == "vyos01"

  - name: set conf vyos02
    vyos_config:
      lines: 
        - set interfaces ethernet eth0 address 10.0.0.4/24
        - set interfaces ethernet eth1 address 172.31.1.4/24
        - set interfaces ethernet eth2 address 172.31.2.4/24
        - set interfaces loopback lo address 2.2.2.2/32
        - set protocols static route 1.1.1.1/32 next-hop 172.31.1.3 distance '10'
        - set protocols static route 1.1.1.1/32 next-hop 172.31.2.3 distance '15'
      save: yes
    when: inventory_hostname == "vyos02"

  - name: show conf after
    vyos_command:
      commands:
        - show configuration command
    register: result
  
  - name: debug config
    debug:
      msg: "{{ result.stdout_lines[0] }}"
